### ISSUE TITLE
FilterError: /bin/sh: 1: django_pyscss.compressor.DjangoScssFilter: not found

### ISSUE THREAD

**Issue by utapyngo** [Kronuz/pyScss#321]
After updating from pyScss 1.2.1 to pyScss 1.3.3 I get this error:

```
compressor.exceptions.FilterError
FilterError: /bin/sh: 1: django_pyscss.compressor.DjangoScssFilter: not found
```

I am using django-compressor==1.4 and django-pyscss==1.0.6.

```
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_pyscss.compressor.DjangoScssFilter'),
)
```

**Comment by rockymeza** [comment]
Hi,

This is actually a bug in [http://github.com/fusionbox/django-pycss](django-pyscss). django-pyscss doesn't currently support the 1.3.x version of pyScss.

Sorry that this is such a late response

**Comment by rockymeza** [comment]
Hi @utapyngo,

django-pyscss now supports pyScss 1.3, you can get it by running:

```
pip install django-pyscss>=2.0.0
```

**Comment by liuguiyangnwpu** [comment]
的确，我使用1.3.0也遇到了问题，centos7.2 默认的cloud软件库就是1.3的。
可以使用[rpm包](https://www.rpmfind.net/linux/rpm2html/search.php?query=python-django-pyscss)或者去python.org找到对应的安装包我使用的是 2.0.2的可以使用！

**Comment by jessehu** [comment]
"pip install django-pyscss --upgrade" make it work on my CentOS 7.2.
