### ISSUE TITLE
statements in if function should not be evaluated unless targeted

### ISSUE THREAD

**Issue by kaaaahhhhnnnn** [Kronuz/pyScss#339]
```sass
color: if(false, <code block A>, <code block B>);
```

According to spec, `code block A` should not be evaluated, but it is.  It's causing issues because I have:

```sass
if($propIndex, nth($strProps, $propIndex), 0);
```

and when `propIndex` is `null`, it throws an error.

My temporary work-around (for anyone else that might have this issue):

```sass
if($propIndex, nth($strProps, $propIndex or 1), 0);
```

**Comment by eevee** [comment]
Fixed in 1.3.5.
