### ISSUE TITLE
currentColor not recognised 

### ISSUE THREAD

**Issue by gregplaysguitar** [Kronuz/pyScss#354]
Example - the following valid css 

    background-image: linear-gradient(to top, transparent, currentColor);

becomes

    background-image: linear-gradient(to top, transparent);

when parsed by pyscss, because `extension/compass._get_gradient_color_stops` is stripping out the currentColor argument.

Information about currentColor here: https://css-tricks.com/currentcolor/

**Comment by eevee** [comment]
Fixed in 1.3.5.
