### ISSUE TITLE
zip_safe not declared

### ISSUE THREAD

**Issue by jensens** [Kronuz/pyScss#367]
While installing ``pyScss`` the following is spit out.

```
zip_safe flag not set; analyzing archive contents...
scss.config: module references __file__
scss.util: module references __file__
```

While it is no tragedy at all, that can be avoided by passing ``zip_safe = False`` to setup (called in function ``run_setup`` in ``setup.py``).

**Comment by Kronuz** [comment]
When did this start to happen? Has this problem always been there?

**Comment by jensens** [comment]
I can not tell about the past, I just noticed the warning after Plone project switched using pyscss as a dependency. Also, it is not a serious problem, just a warning. In order trying to be a good citizen in FOSS world I reported my findings.
