### ISSUE TITLE
Future warning - unicode nested set

### ISSUE THREAD

**Issue by msoucy** [Kronuz/pyScss#376]
```
Python 3.7.1 (default, Nov  5 2018, 14:07:04) 
[GCC 8.2.1 20181011 (Red Hat 8.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scss import Compiler
/home/msoucy/Code/project/.venv/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
```

The fix is introduced in [the 3.7 release notes](https://docs.python.org/dev/whatsnew/3.7.html#changes-in-the-python-api), though I wasn't exactly sure which part of that large regex was the problematic area.

**Comment by ginomempin** [comment]
I got the error to go away by escaping one of the `[` in selector.py:

BEFORE:
```
    # Square brackets are attribute tests
    # TODO: this doesn't handle ] within a string
    | [[] .+? []]
```

AFTER (escape the 2nd `[`):
```
    # Square brackets are attribute tests
    # TODO: this doesn't handle ] within a string
    | [\[] .+? []]
```

Python 3.7.0
pyScss==1.3.5

**Comment by Registrierungsgenervter** [comment]
you can also just write

```
| \[ .+? \]
```

---

@Kronuz It is four months later, how ´bout updating the PyPI package?

**Comment by lamby** [comment]
> @Kronuz It is four months later, how ´bout updating the PyPI package?

Ping on this? :)

**Comment by coridrew** [comment]
This is blocking me as well

**Comment by jmduke** [comment]
Added a PR to fix this:

https://github.com/Kronuz/pyScss/pull/381

**Comment by cherryleafroad** [comment]
I had to fix this manually. Oh well, thanks for the fix @jmduke
