### ISSUE TITLE
No tags for 1.3.6 and 1.3.7

### ISSUE THREAD

**Issue by amotoki** [Kronuz/pyScss#414]
We find 1.3.6 and 1.3.7 releases in PyPI https://pypi.org/project/pyScss/#history but there are no corresponding tags in the git repository. It would be really nice if you create these tags.

**Comment by e0ne** [comment]
@amotoki all tags exist in the repo: https://github.com/Kronuz/pyScss/tags:
- https://github.com/Kronuz/pyScss/releases/tag/1.3.6
- https://github.com/Kronuz/pyScss/releases/tag/1.3.7

**Comment by amotoki** [comment]
Thanks. I did not noticed them as they used different tag naming convention.
